// izfree Tools for Windows Installer 1.0
// Copyright (C) 2001 Pahvant Technologies, Inc.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// guidgen.idl : IDL source for guidgen.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (guidgen.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

/////////////////////////////////////////////////////////////////////////////
[
    object,
    uuid(67E7999E-9B44-4CB3-974A-235670564EC8),
    dual,
    helpstring("IGenerator Interface"),
    pointer_default(unique)
]
interface IGenerator : IDispatch
{
    [id(1), helpstring("method Generate")]
    HRESULT Generate([out, retval] BSTR *guid);
};

/////////////////////////////////////////////////////////////////////////////
[
    object,
    uuid(D242E8F4-F93F-408D-B0CB-0AF9F9851E5F),
    dual,
    helpstring("IFileVersion Interface"),
    pointer_default(unique)
]
interface IFileVersion : IDispatch
{
    [propget, id(1), helpstring("property Version")]
    HRESULT Version([in] BSTR file, [out, retval] BSTR *pVal);
};

/////////////////////////////////////////////////////////////////////////////
[
    uuid(699E2EC2-F86C-4360-BA1E-F01DD5AA5BAC),
    version(1.0),
    helpstring("guidgen 1.0 Type Library")
]
library GUIDGENLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(221E47F3-2F9B-4A88-BD14-7719E41550BC),
        helpstring("Generator Class")
    ]
    coclass Generator
    {
        [default] interface IGenerator;
    };
    [
        uuid(0098849C-76BB-423F-B54E-AF34B5849098),
        helpstring("FileVersion Class")
    ]
    coclass FileVersion
    {
        [default] interface IFileVersion;
    };
};
